#  Template NodeJS build

#  This template allows you to validate your NodeJS code.
#  The workflow allows running tests and code linting on the default branch.

image: node:10.15.3

pipelines:
  default:
    - parallel:
      - step:
          name: Build & Test
          caches:
            - node
          script:
            - yarn install
            - yarn deploy:test         
      - step:
          name: Code linting
          script:
            - npm install eslint
            - npx eslint .
          caches:
            - node              